### ISSUE TITLE
CI new pull request always fails?

### ISSUE THREAD

**Issue by nahakyuu** [yiisoft/actions#52]
https://github.com/yiisoft/yii-debug-api/actions/workflows/rector.yml?query=is%3Afailure

**Comment by vjik** [comment]
Rector workflow make commit and now fail on pull request from forks.

Can you try change `/.github/workflow/rector.yml` in your PR to this code:

```
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: rector

jobs:
  rector:
    uses: yiisoft/actions/.github/workflows/rector.yml@master
    secrets:
      token: ${{ secrets.YIISOFT_GITHUB_TOKEN }}
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.0']
```

?
